-- ============================================================================
-- Corrige a flag has_stock_control pra produtos que não estavam nos 48 IDs
-- fixos do seed original, mas que ainda assim só usam materiais genéricos
-- (sem estoque real) -- ex.: "NECESSAIRE SHELBY", que não está no
-- seed_bolsas.sql mas usa "Cursor", "Etiqueta em Couro / Cetim" etc.
--
-- Critério: desliga o controle de estoque de qualquer produto que NÃO tenha
-- nenhum material da ficha entre os 186 materiais reais sincronizados
-- (sync_materiais_atelie_bolsas.sql). Não mexe em produto que já usa pelo
-- menos um material real -- esses continuam com o valor que já tinham.
-- ============================================================================

update public.products p
set has_stock_control = false
where p.owner_id = '62f88a4b-a969-4f1a-8150-bfd21787abee'
  and exists (select 1 from public.product_materials pm where pm.product_id = p.id)
  and not exists (
    select 1
    from public.product_materials pm
    join public.materials m on m.id = pm.material_id
    where pm.product_id = p.id
      and m.name in (
    'ALÇA CADARÇO LARANJA (1,5 CM)', 'ALÇA CADARÇO PRETO (1,5 CM)', 'ALÇA CADARÇO VERDE MUSGO (1,5 CM)', 'ALÇA CHIQUE AZUL MARINHO (3 CM)',
      'ALÇA CHIQUE LARANJA (3 CM)', 'ALÇA CHIQUE LISTRAS BEGE/PRETO/AREIA (3 CM)', 'ALÇA CHIQUE LISTRAS VERDE/VERMELHO (4 CM)', 'ALÇA CHIQUE PINK FLUOR (3 CM)',
      'ALÇA CHIQUE PRETO (2 CM)', 'ALÇA CHIQUE PRETO (3 CM)', 'ALÇA CHIQUE ROXO (3 CM)', 'ALÇA CHIQUE TELHA (3 CM)',
      'ALÇA ESTAMPADA FOLHAGEM COLORS (3 CM)', 'ALÇA PRETA PRONTA EM SINTÉTICO (2,5 CM)', 'ARGOLA PRATA CHAVEIRO (2,4 CM)', 'BOTÃO IMÃ OURO VELHO (1,8 CM)',
      'BOTÃO IMÃ PRATA (1,8 CM)', 'CARTÃO DE AGRADECIMENTO', 'CARTÃO ETIQUETA SUJINHO LIMPINHO', 'CORDÃO AZUL ROYAL',
      'CORINO PALHA MARROM MATELASSE (140)', 'CORRENTE ALUMINIO NIQUEL (10.8MMX15.2MM)', 'CORRENTE ALUMINIO OURO (10.8MMX15.2MM)', 'CORRENTE DOURADO (1,8 MM)',
      'CORRENTE GRAFITE (1,8 MM)', 'CORRENTE PRATA (1,8 MM)', 'COURVIN 0.8 LBR CAFÉ (1.40 X 40)', 'COURVIN 1.0 CASCO PRETO (1.40 X 40)',
      'COURVIN 1.0 MAUI XADREZ BEGE (140X25)', 'COURVIN 1.0 PRADA VINHO (140X25)', 'COURVIN 1.2 JACARÉ MARRON (140X25)', 'COURVIN 1.2 JACARÉ PRETO (1,40 X 25)',
      'COURVIN 1.8 SOFT COLOR MARROM/BEGE (140)', 'COURVIN 1.8 SOFT COLOR PRETO / VERMELHO (1.40 X 25)', 'COURVIN 1.8 SOFT COLOR PRETO/PRETO (140)', 'COURVIN DUNAS MOSTARDA 0,9 (1,40)',
      'COURVIN DUNE 0,8 - AZUL MARINHO', 'COURVIN DUNE 0,8 - CAFÉ', 'COURVIN DUNE 0,8 - GRAFITE (140)', 'COURVIN URUGUAI DIAMANTE PRETO ACOPLADO (5MM - D26) (1.50)',
      'CRISTAL COLOR LARANJA (0,40)', 'CRISTAL COLOR PINK (0,40)', 'CRISTAL COLOR PRETO (0,40)', 'CRISTAL FOSCO ALKLEAR TRANSPARENTE (0,40) (1,40)',
      'CURSOR 05 VISLON JACARE CINZA (TRATORADO)', 'CURSOR 05 VISLON JACARE PRETO (TRATORADO)', 'CURSOR 06 CORAÇÃO AMOR NIQUEL', 'CURSOR 06 CORAÇÃO AMOR OURO',
      'CURSOR 06 NIQUEL PINGENTE ONDULADO', 'CURSOR 06 NIQUELADO, BRONZE, DOURADO', 'CURSOR 06 NÍQUEL SIMPLES', 'CURSOR 06 OURO CATAFORETICO SIMPLES',
      'CURSOR 06 OURO PINGENTE ONDULADO', 'CURSOR 06 OURO VELHO PINGENTE ONDULADO', 'CURSOR 06 OURO VELHO SIMPLES', 'CURSOR 06 PALITO NIQUELADO',
      'CURSOR 06 PINGENTE LAÇO NÍQUEL', 'CURSOR 06 PINGENTE LAÇO OURO', 'CURSOR 06 PINGO VAZADO OURO', 'CURSOR 06 PLASTIC PRETO',
      'CURSOR 06 PRETO SIMPLES', 'CURSOR 06 VAZADO NIGUEL', 'CURSOR 06 VAZADO PRETO', 'CURSOR 08 OURO VELHO SIMPLES',
      'ESPAGUETE (3 MM)', 'ESPUMA 10MM', 'ETIQUETA COURO SINTÉTICO GRAVADA E CORTADA', 'ETIQUETA DE CETIM PERSONALIZADA',
      'ETIQUETA METAL DOURADO', 'ETIQUETA METAL ONIX', 'ETIQUETA METAL OURO VELHO', 'ETIQUETA METAL PRATA',
      'EVA BRANCO (2 CM 1,40X50)', 'EVA PRETO (2CM 1,40X50)', 'FITA DE CETIM AMARELO GEMA 10 METROS (2 CM)', 'FITA DE CETIM AZUL PROFUNDO - 10 M - (2 CM)',
      'FITA DE CETIM BORDO - 10M - (2 CM)', 'FITA DE CETIM CINZA - 10M (2 CM)', 'FITA DE CETIM CINZA - 10M - (2 CM)', 'FITA DUPLA FACE 4MM',
      'FITA DUPLA FACE 8MM', 'KIT COMPLETO COM SUPORTE PARA CELULAR', 'LINHA CIFA 40 BRANCO', 'LINHA CIFA 60 PRETO 80G',
      'LONA DE ALGODAO ENCERADA MOSTARDA (1,50X50)', 'MEIA ARGOLA NIQUEL (1,5CM)', 'MEIA ARGOLA NIQUEL (2 CM)', 'MEIA ARGOLA NIQUEL (2,5CM)',
      'MEIA ARGOLA NIQUEL (3 CM)', 'MEIA ARGOLA ONIX (2 CM)', 'MEIA ARGOLA ONIX (2,5 CM)', 'MEIA ARGOLA OURO CATAFORÉTICO (2 CM)',
      'MEIA ARGOLA OURO VELHO (1,5 CM)', 'MEIA ARGOLA OURO VELHO (2 CM)', 'MEIA ARGOLA OURO VELHO (2,5 CM)', 'MEIA ARGOLA OURO VELHO (3 CM)',
      'MOSQUETAO ONIX (3 CM)', 'MOSQUETAO OURO VELHO (2,5 CM)', 'MOSQUETAO OURO VELHO (3 CM)', 'MOSQUETÃO NIQUEL (2 CM)',
      'MOSQUETÃO NIQUEL ALTERO (2,5 CM)', 'MOSQUETÃO ONIX (1,5 CM)', 'MOSQUETÃO ONIX (2 CM)', 'MOSQUETÃO OURO (2 CM)',
      'MOSQUETÃO OURO CATAFORÉTICO (1,5 CM)', 'MOSQUETÃO OURO VELHO (1,5 CM)', 'MOSQUETÃO OURO VELHO (2 CM)', 'NAPA BAGUM PRETO',
      'NAPA BRANCA KL (2800)', 'NAPA COURVIN PRETO', 'NYLON 70 EMBORRACHADO CINZA CHUMBO (1,50X100)', 'NYLON 70 EMBORRACHADO PRETO',
      'NYLON POLIESTER ULY PRETO (1680)', 'NYLON PVC 70 - (VERDE / AMARELO / VERMELHO / CINZA, PRETO)', 'NYLON RESINADO VERMELHO 150', 'PAPELÃO COURO',
      'PLÁSTICO CRISTAL (30 G) (1.40)', 'POLIESTER 300/300 PRETO', 'POLIESTER 300/300 VERDE MILITAR', 'POLIESTER PVC 600 LARANJA (150X50)',
      'POLIESTER PVC 600 VERDE MUSGO (150X50)', 'PORTA BOBINA CIRCULAR DE SILICONE', 'QUADRO NÍQUEL (1,5 CM)', 'QUADRO OURO VELHO (1,5 CM)',
      'QUADRO ÔNIX (1,5 CM)', 'REGUA DE AÇO INOX 100 CM', 'REGULADOR MINE NIQUEL (1,5 CM)', 'REGULADOR NIQUEL (1,5 CM)',
      'REGULADOR NIQUEL (2 CM)', 'REGULADOR NIQUEL (2,5 CM)', 'REGULADOR NÍQUEL (3 CM)', 'REGULADOR OURO (2 CM)',
      'REGULADOR OURO CATAFORETICO (3 CM)', 'REGULADOR OURO VELHO (1,5 CM)', 'REGULADOR OURO VELHO (2 CM)', 'REGULADOR OURO VELHO (2,5 CM)',
      'REGULADOR OURO VELHO (3 CM)', 'REGULADOR ÔNIX (1,5 CM)', 'REGULADOR ÔNIX (2 CM)', 'REGULADOR ÔNIX (2,5 CM)',
      'SINTÉTICO TAG ARM CAFÉ GT', 'TEKBOND ADESIVO INSTANTANEO 793 20GR', 'TELA PARA MOCHILA CARAMELO', 'TELA PARA MOCHILA PRETO',
      'TELA RENDA EMBORRACHADA AMARELO CANÁRIO (140)', 'TELA RENDA EMBORRACHADA AZUL MARINHO (140)', 'TELA RENDA EMBORRACHADA BEGE ESCURO (140)', 'TELA RENDA EMBORRACHADA LARANJA (140)',
      'TESOURA DE PRECISÃO CABO SOFT 6,5 POLEGADAS 17 CM', 'TIRA DE COURO SINTÉTICO CAFE', 'TIRA DE COURO SINTÉTICO CARAMELO', 'TIRA DE COURO SINTÉTICO PRETO',
      'TNT BRANCO (150GR)', 'TNT BRANCO 80 (140X25)', 'TNT CINZA CHUMBO 80 (140X25)', 'TNT LARANJA (1.40)',
      'TRICOLINE 100% ALGODÃO COLORIDO', 'VELKRO PRETO (2,5 CM)', 'VIES DESTAQUE 35X20', 'VIVO BRILHO MARRON (4/11)',
      'VIVO BRILHO PRETO (4/11)', 'VIVO BRILHO ROSA PINK (4/11)', 'VIVO BRILHO VERDE MUSGO (4/11)', 'VIÉS DESTAQUE AZUL ROYAL (35MM)',
      'VIÉS DESTAQUE COR 21 - VERMELHO (23 MM 20 METROS)', 'VIÉS DESTAQUE COR 33 CAQUI/BEGE ESCURO (2,3 CM 20 METROS)', 'VIÉS DESTAQUE ROSA PINK (35MM)', 'ZIPER 05 VISLON JACARE PRETO/CINZA (TRATORADO)',
      'ZIPER 05 VISLON JACARE PRETO/PRETO (TRATORADO)', 'ZIPER 06 AMARELO OURO', 'ZIPER 06 AZUL BIC', 'ZIPER 06 AZUL MARINHO',
      'ZIPER 06 AZUL ROYAL', 'ZIPER 06 AZUL TIFANY', 'ZIPER 06 BEGE KAKI', 'ZIPER 06 LARANJA',
      'ZIPER 06 PINK', 'ZIPER 06 PRETO', 'ZIPER 06 PUXADOR GRANDE CAFÉ (60CM)', 'ZIPER 06 PUXADOR GRANDE VERDE MUSGO (60CM)',
      'ZIPER 06 ROXO', 'ZIPER 06 TELHA', 'ZIPER 08 VINHO', 'ZIPER 5 BRANCO',
      'ZIPER 5 CINZA CHUMBO', 'ZIPER 5 MARFIM'
    )
  );
